### ISSUE TITLE
utf-8 codec error

### ISSUE THREAD

**Issue by carlnykvist** [icyguider/MoreImpacketExamples#2]
Hi,

I'm getting this error when trying to use one of your scripts. Have you faced this before?

![image](https://user-images.githubusercontent.com/5971228/216379107-c862ed12-dcc8-4bf7-8e08-0171650a72bc.png)

**Comment by icyguider** [comment]
Yes, I have seen that error before. This is why if you tried to look at the source code of the script, you would see that I specifically programmed error handling for it. But if we only look at what your screenshot is showing, we can easily see it's telling us that a "Timeout occurred when trying to read output or cleanup".  

So based on that, you have to ask yourself, why was the script not able to get output? Is the program executing successfully? Could AV be blocking the AMSI bypass being used? Is the script for some reason failing to write output to the specified registry? These are all questions that could be easily answered by modifying the source code and doing some basic debugging.

If you do not want to modify the provided scripts or perform basic debugging, I really wouldn't bother trying to use them. They are **not** meant to "just work" in all circumstances and I have purposefully implemented some bad OPSEC in the scripts to make them less useful to random skids who aren't trying to learn anything. I will repost the relevant section of the README since some people seem to be missing what the point of this project is:

![image](https://user-images.githubusercontent.com/79864975/218173536-ad0c3dc5-eac3-431d-8ba0-0a9286c1704b.png)

I will be closing this issue since it doesn't make sense in the context of this project's described purpose.
